### ISSUE TITLE
Results/Performance

### ISSUE THREAD

**Issue by uditsaxena** [kelayamatoz/BiDAF-PyTorch#1]
Hey, 

Could you talk a bit about your results on the squad dataset?

I was wondering what the performance was.

Thanks

**Comment by kelayamatoz** [comment]
This repo is not completed. I was working on reproducing the BiDAF paper in pytorch until  the Allen Institute team published their official pytorch BiDAF. You can view their results at https://github.com/allenai/allennlp.

**Comment by juexZZ** [comment]
@kelayamatoz Hi, I was looking for a pytorch version of BiDAF when I saw this repo. Can you please tell me where the code of the BiDAF model is in their repo: https://github.com/allenai/allennlp  ?
I'm a newbie and get quite confused by so many files in the Allen Institute's repo. Thank you very much! 👍

**Comment by kelayamatoz** [comment]
https://github.com/allenai/allennlp/tree/master/allennlp/models/reading_comprehension
