### ISSUE TITLE
No such file or directory: "out/basic/00/shared.json"

### ISSUE THREAD

**Issue by sharejing** [kelayamatoz/BiDAF-PyTorch#2]
hello. when I run python  -m bidaf.cli --mode train, I meet a error: No such file or directory: "out/basic/00/shared.json".  Can you help me? Thanks

**Comment by kelayamatoz** [comment]
Hi Sharejing, this repo is a toy example that only specifies the compute graph. I didn't add the training pipeline as there wasn't a SQuAD dataset parser available in PyTorch back in the day. Not sure if there is one now.

For a more complete example you can check the AllenNLP's official implementation at: https://github.com/allenai/allennlp/blob/master/allennlp/models/reading_comprehension/bidaf.py.

**Comment by sharejing** [comment]
Hi, kelayamatoz. I' m glad to receive your reply. I'll be that, thank you!
